module.exports = {
    PING: 1,
    APPLICATION_COMMAND: 2,
    MESSAGE_COMPONENT: 3,
    APPLICATION_COMMAND_AUTOCOMPLETE: 4,
    MODAL_SUBMIT: 5,
    1: 'PING',
    2: 'APPLICATION_COMMAND',
    3: 'MESSAGE_COMPONENT',
    4: 'APPLICATION_COMMAND_AUTOCOMPLETE',
    5: 'MODAL_SUBMIT'
};